---
- name: Configure EC2 Instance with Docker
  hosts: WebApp-EC2
  become: yes
  vars:
    docker_users:
      - ec2-user

  tasks:
    - name: Update packages for Amazon Linux/CentOS
      yum:
        name: '*'
        state: latest

    - name: Install dependencies
      yum:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
        state: present

    - name: Add Docker repository
      shell: |
        amazon-linux-extras enable docker
        yum clean metadata

    - name: Install Docker
      yum:
        name: docker
        state: present

    - name: Start and enable Docker
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Add user to Docker group
      user:
        name: "{{ item }}"
        groups: docker
        append: yes
      loop: "{{ docker_users }}"
